experiment:
  name: cape/cgqa
dataset:
  # data_dir: /home/shan/czsl/transform-czsl/dataset/datasets/cgqa/cgqa/
  data_dir: /media/talha/79e18c32-24dc-4291-918a-8b00897939e13/czsl/czsl/transform-czsl/dataset/datasets/cgqa/
  dataset: cgqa
  splitname: compositional-split-natural
  open_world: false
model_params:
  model: cape
  composition: true
  dropout: true
  norm: true
  nhead: 6
  zsl: false
  nlayers:
  fc_emb: 768,1024,1200
  gr_emb: d4096,d
  learn_emb: true
  single_dualencoder: false
  image_embedder: false
  emb_dim: 512
  emb_init: word2vec
  graph_init: null
  eval_type: otherdist
  project_features: false
  image_extractor_type: resnet18
  image_extractor: resnet18
  self_atten: true
  train_only: true
  static_inp: false
gcnii:
  hidden_dim: 1024
  gcn_type: gcn
  gcn_nlayers: 10
training:
  batch_size: 30
  word_embed_dim: 300
  eval_val_every: 2
  load:
  lr: 5.0e-05
  replace_decoder_with_mlp: true
  wd: 5.0e-05
  lrg: 5.0e-06
  margin: 2
  margin: 0.4
  cosine_coeficient: 100
  max_epochs: 120
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  random_crop: true
  workers: 8
  feature_dim: 512
  update_features: true
  freeze_featues: false
